server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
        format_sql: true
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: local

jwt:
  secret:
    key: WvG406dyLBEesRAwcYAKSA4PicZkO/iBAFB93NLYF4k=

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: hojin-spring-profile-imgs